#ifndef LIBRARY_SPIIMOTIONCONTROLLER_GLOBAL_H
#define LIBRARY_SPIIMOTIONCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBRARY_SPIIMOTIONCONTROLLER_LIBRARY)
#  define LIBRARY_SPIIMOTIONCONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBRARY_SPIIMOTIONCONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBRARY_SPIIMOTIONCONTROLLER_GLOBAL_H
