#ifndef LIBRARY_SPIIMOTIONCONTROLLER_GLOBAL_H
#define LIBRARY_SPIIMOTIONCONTROLLER_GLOBAL_H

#include "SPII_Version.h"

#ifdef _MSC_VER
#  if defined(LIBRARY_SPIIMOTIONCONTROLLER_LIBRARY)
#    define LIBRARY_SPIIMOTIONCONTROLLERSHARED_EXPORT __declspec(dllexport)
#  else
#    define LIBRARY_SPIIMOTIONCONTROLLERSHARED_EXPORT __declspec(dllexport)
#  endif
#else
#  define LIBRARY_SPIIMOTIONCONTROLLERSHARED_EXPORT
#endif


#endif // LIBRARY_SPIIMOTIONCONTROLLER_GLOBAL_H
