#ifndef LIBRARY_RIGOL_OSCILLOSCOPE_GLOBAL_H
#define LIBRARY_RIGOL_OSCILLOSCOPE_GLOBAL_H

#ifdef _MSC_VER
#  if defined(LIBRARY_RIGOL_OSCILLOSCOPE_LIBRARY)
#    define LIBRARY_RIGOL_OSCILLOSCOPESHARED_EXPORT __declspec(dllexport)
#  else
#    define LIBRARY_RIGOL_OSCILLOSCOPESHARED_EXPORT __declspec(dllexport)
#  endif
#else
#  define LIBRARY_RIGOL_OSCILLOSCOPESHARED_EXPORT
#endif

#endif // LIBRARY_MUNK_POWER_SUPPLY_GLOBAL_H
