.TH "library_munk_power_supply/data Directory Reference" 3 "Mon Jun 19 2017" "ECM Control System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
library_munk_power_supply/data Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBregister_data_object\&.cpp\fP"
.br
.ti -1c
.RI "file \fBregister_data_object\&.h\fP"
.br
.ti -1c
.RI "file \fBtype_current_factor\&.h\fP"
.br
.ti -1c
.RI "file \fBtype_current_set\&.h\fP"
.br
.ti -1c
.RI "file \fBtype_current_voltage_prescale\&.h\fP"
.br
.ti -1c
.RI "file \fBtype_prescalar_power\&.h\fP"
.br
.ti -1c
.RI "file \fBtype_read_write\&.h\fP"
.br
.ti -1c
.RI "file \fBtype_segment_level\&.h\fP"
.br
.ti -1c
.RI "file \fBtype_segment_mode\&.h\fP"
.br
.ti -1c
.RI "file \fBtype_segment_parameter\&.h\fP"
.br
.ti -1c
.RI "file \fBtype_voltage_set\&.h\fP"
.br
.in -1c
