.TH "src/library_munk_power_supply/data_registers Directory Reference" 3 "Tue Jun 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/library_munk_power_supply/data_registers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBabstract_parameter\&.cpp\fP"
.br
.ti -1c
.RI "file \fBabstract_parameter\&.h\fP"
.br
.ti -1c
.RI "file \fBparameter_memory_write\&.cpp\fP"
.br
.ti -1c
.RI "file \fBparameter_memory_write\&.h\fP"
.br
.ti -1c
.RI "file \fBsegment_current_setpoint\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsegment_current_setpoint\&.h\fP"
.br
.ti -1c
.RI "file \fBsegment_time_data_detailed\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsegment_time_data_detailed\&.h\fP"
.br
.ti -1c
.RI "file \fBsegment_time_data_general\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsegment_time_data_general\&.h\fP"
.br
.ti -1c
.RI "file \fBsegment_time_detailed\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsegment_time_detailed\&.h\fP"
.br
.ti -1c
.RI "file \fBsegment_time_general\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsegment_time_general\&.h\fP"
.br
.ti -1c
.RI "file \fBsegment_voltage_setpoint\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsegment_voltage_setpoint\&.h\fP"
.br
.ti -1c
.RI "file \fBtype_definition\&.h\fP"
.br
.in -1c
