.TH "common/common.h" 3 "Mon Jun 19 2017" "ECM Control System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/common.h
.SH SYNOPSIS
.br
.PP
\fC#include 'common_global\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommon\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUNUSED\fP(x)   (void)(x)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define UNUSED(x)   (void)(x)"

.PP
Definition at line 6 of file common\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ECM Control System from the source code\&.
