.TH "Common" 3 "Mon Jun 19 2017" "ECM Control System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Common
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <common\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommon\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file common\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Common::Common ()"

.PP
Definition at line 4 of file common\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECM Control System from the source code\&.
