.TH "Data::RegisterDataObject" 3 "Mon Jun 19 2017" "ECM Control System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Data::RegisterDataObject \- The \fBRegisterDataObject\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <register_data_object\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegisterDataObject\fP ()"
.br
.RI "\fBRegisterDataObject\fP\&. "
.ti -1c
.RI "\fBRegisterDataObject\fP (const int &\fBvoltage\fP, const int &\fBcurrent\fP)"
.br
.RI "\fBRegisterDataObject\fP\&. "
.ti -1c
.RI "\fBRegisterDataObject\fP (const \fBRegisterDataObject\fP &obj)"
.br
.RI "\fBRegisterDataObject\fP\&. "
.ti -1c
.RI "void \fBoperator=\fP (const \fBRegisterDataObject\fP &rhs)"
.br
.RI "operator = "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBRegisterDataObject\fP &rhs) const"
.br
.RI "operator < "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBRegisterDataObject\fP &rhs) const"
.br
.RI "operator == "
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBRegisterDataObject\fP &rhs) const"
.br
.RI "operator != "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvoltage\fP"
.br
.RI "voltage "
.ti -1c
.RI "int \fBcurrent\fP"
.br
.RI "current "
.in -1c
.SH "Detailed Description"
.PP 
The \fBRegisterDataObject\fP class\&. 
.PP
Definition at line 15 of file register_data_object\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Data::RegisterDataObject::RegisterDataObject ()"

.PP
\fBRegisterDataObject\fP\&. 
.PP
Definition at line 5 of file register_data_object\&.cpp\&.
.SS "Data::RegisterDataObject::RegisterDataObject (const int & voltage, const int & current)"

.PP
\fBRegisterDataObject\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoltage\fP 
.br
\fIcurrent\fP 
.RE
.PP

.PP
Definition at line 11 of file register_data_object\&.cpp\&.
.SS "Data::RegisterDataObject::RegisterDataObject (const \fBRegisterDataObject\fP & obj)"

.PP
\fBRegisterDataObject\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIobj\fP 
.RE
.PP

.PP
Definition at line 17 of file register_data_object\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Data::RegisterDataObject::operator!= (const \fBRegisterDataObject\fP & rhs) const"

.PP
operator != 
.PP
\fBParameters:\fP
.RS 4
\fIrhs\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 58 of file register_data_object\&.cpp\&.
.SS "bool Data::RegisterDataObject::operator< (const \fBRegisterDataObject\fP & rhs) const"

.PP
operator < 
.PP
\fBParameters:\fP
.RS 4
\fIrhs\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 29 of file register_data_object\&.cpp\&.
.SS "void Data::RegisterDataObject::operator= (const \fBRegisterDataObject\fP & rhs)"

.PP
operator = 
.PP
\fBParameters:\fP
.RS 4
\fIrhs\fP 
.RE
.PP

.PP
Definition at line 23 of file register_data_object\&.cpp\&.
.SS "bool Data::RegisterDataObject::operator== (const \fBRegisterDataObject\fP & rhs) const"

.PP
operator == 
.PP
\fBParameters:\fP
.RS 4
\fIrhs\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 49 of file register_data_object\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int Data::RegisterDataObject::current"

.PP
current 
.PP
Definition at line 73 of file register_data_object\&.h\&.
.SS "int Data::RegisterDataObject::voltage"

.PP
voltage 
.PP
Definition at line 68 of file register_data_object\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECM Control System from the source code\&.
