.TH "DataParameter::SegmentTimeDataGeneral" 3 "Tue Jun 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataParameter::SegmentTimeDataGeneral \- The \fBSegmentTimeDataGeneral\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <segment_time_data_general\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSegmentTimeDataGeneral\fP ()"
.br
.RI "\fBSegmentTimeDataGeneral\fP\&. "
.ti -1c
.RI "\fBSegmentTimeDataGeneral\fP (const \fBData::SegmentLevel\fP &level, const \fBData::SegmentMode\fP &mode, const \fBData::SegmentPower\fP &power, const uint8_t &time)"
.br
.RI "\fBSegmentTimeDataGeneral\fP\&. "
.ti -1c
.RI "void \fBsetSegmentLevel\fP (const \fBData::SegmentLevel\fP &level)"
.br
.RI "setSegmentLevel "
.ti -1c
.RI "void \fBsetSegmentMode\fP (const \fBData::SegmentMode\fP &mode)"
.br
.RI "setSegmentMode "
.ti -1c
.RI "void \fBsetSegmentPower\fP (const \fBData::SegmentPower\fP &power)"
.br
.RI "setSegmentPower "
.ti -1c
.RI "void \fBsetTimeValue\fP (const uint8_t &time)"
.br
.RI "setTimeValue "
.ti -1c
.RI "void \fBresetData\fP ()"
.br
.RI "resetData "
.ti -1c
.RI "void \fBupdateData\fP (const \fBSegmentTimeDataGeneral\fP &data)"
.br
.RI "updateData "
.ti -1c
.RI "uint32_t \fBgetConstructedBitArray\fP () const"
.br
.RI "getConstructedBitArray "
.ti -1c
.RI "void \fBoperator=\fP (const \fBSegmentTimeDataGeneral\fP &rhs)"
.br
.RI "operator = "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBSegmentTimeDataGeneral\fP &rhs) const"
.br
.RI "operator == "
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBSegmentTimeDataGeneral\fP &rhs) const"
.br
.RI "operator != "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBData::SegmentLevel\fP \fBsegmentLevel\fP"
.br
.RI "segmentLevel "
.ti -1c
.RI "\fBData::SegmentMode\fP \fBsegmentMode\fP"
.br
.RI "segmentMode "
.ti -1c
.RI "\fBData::SegmentPower\fP \fBsegmentPower\fP"
.br
.RI "segmentPower "
.ti -1c
.RI "uint8_t \fBtimeValue\fP"
.br
.RI "timeValue "
.in -1c
.SH "Detailed Description"
.PP 
The \fBSegmentTimeDataGeneral\fP class\&. 
.PP
Definition at line 14 of file segment_time_data_general\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DataParameter::SegmentTimeDataGeneral::SegmentTimeDataGeneral ()"

.PP
\fBSegmentTimeDataGeneral\fP\&. 
.PP
Definition at line 5 of file segment_time_data_general\&.cpp\&.
.SS "DataParameter::SegmentTimeDataGeneral::SegmentTimeDataGeneral (const \fBData::SegmentLevel\fP & level, const \fBData::SegmentMode\fP & mode, const \fBData::SegmentPower\fP & power, const uint8_t & time)"

.PP
\fBSegmentTimeDataGeneral\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlevel\fP 
.br
\fImode\fP 
.br
\fIpower\fP 
.br
\fItime\fP 
.RE
.PP

.PP
Definition at line 11 of file segment_time_data_general\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "uint32_t DataParameter::SegmentTimeDataGeneral::getConstructedBitArray () const"

.PP
getConstructedBitArray 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 64 of file segment_time_data_general\&.cpp\&.
.SS "bool DataParameter::SegmentTimeDataGeneral::operator!= (const \fBSegmentTimeDataGeneral\fP & rhs) const\fC [inline]\fP"

.PP
operator != 
.PP
\fBParameters:\fP
.RS 4
\fIrhs\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 114 of file segment_time_data_general\&.h\&.
.SS "void DataParameter::SegmentTimeDataGeneral::operator= (const \fBSegmentTimeDataGeneral\fP & rhs)\fC [inline]\fP"

.PP
operator = 
.PP
\fBParameters:\fP
.RS 4
\fIrhs\fP 
.RE
.PP

.PP
Definition at line 79 of file segment_time_data_general\&.h\&.
.SS "bool DataParameter::SegmentTimeDataGeneral::operator== (const \fBSegmentTimeDataGeneral\fP & rhs) const\fC [inline]\fP"

.PP
operator == 
.PP
\fBParameters:\fP
.RS 4
\fIrhs\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 92 of file segment_time_data_general\&.h\&.
.SS "void DataParameter::SegmentTimeDataGeneral::resetData ()"

.PP
resetData 
.PP
Definition at line 77 of file segment_time_data_general\&.cpp\&.
.SS "void DataParameter::SegmentTimeDataGeneral::setSegmentLevel (const \fBData::SegmentLevel\fP & level)"

.PP
setSegmentLevel 
.PP
\fBParameters:\fP
.RS 4
\fIlevel\fP 
.RE
.PP

.PP
Definition at line 20 of file segment_time_data_general\&.cpp\&.
.SS "void DataParameter::SegmentTimeDataGeneral::setSegmentMode (const \fBData::SegmentMode\fP & mode)"

.PP
setSegmentMode 
.PP
\fBParameters:\fP
.RS 4
\fImode\fP 
.RE
.PP

.PP
Definition at line 37 of file segment_time_data_general\&.cpp\&.
.SS "void DataParameter::SegmentTimeDataGeneral::setSegmentPower (const \fBData::SegmentPower\fP & power)"

.PP
setSegmentPower 
.PP
\fBParameters:\fP
.RS 4
\fIpower\fP 
.RE
.PP

.PP
Definition at line 48 of file segment_time_data_general\&.cpp\&.
.SS "void DataParameter::SegmentTimeDataGeneral::setTimeValue (const uint8_t & time)"

.PP
setTimeValue 
.PP
\fBParameters:\fP
.RS 4
\fItime\fP 
.RE
.PP

.PP
Definition at line 53 of file segment_time_data_general\&.cpp\&.
.SS "void DataParameter::SegmentTimeDataGeneral::updateData (const \fBSegmentTimeDataGeneral\fP & data)"

.PP
updateData 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP 
.RE
.PP

.PP
Definition at line 85 of file segment_time_data_general\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBData::SegmentLevel\fP DataParameter::SegmentTimeDataGeneral::segmentLevel\fC [private]\fP"

.PP
segmentLevel 
.PP
Definition at line 122 of file segment_time_data_general\&.h\&.
.SS "\fBData::SegmentMode\fP DataParameter::SegmentTimeDataGeneral::segmentMode\fC [private]\fP"

.PP
segmentMode 
.PP
Definition at line 127 of file segment_time_data_general\&.h\&.
.SS "\fBData::SegmentPower\fP DataParameter::SegmentTimeDataGeneral::segmentPower\fC [private]\fP"

.PP
segmentPower 
.PP
Definition at line 132 of file segment_time_data_general\&.h\&.
.SS "uint8_t DataParameter::SegmentTimeDataGeneral::timeValue\fC [private]\fP"

.PP
timeValue 
.PP
Definition at line 137 of file segment_time_data_general\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
