.TH "DataParameter::ParameterMemoryWrite" 3 "Tue Jun 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataParameter::ParameterMemoryWrite \- The \fBParameterMemoryWrite\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parameter_memory_write\&.h>\fP
.PP
Inherits \fBDataParameter::AbstractParameter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParameterMemoryWrite\fP ()"
.br
.RI "\fBParameterMemoryWrite\fP\&. "
.ti -1c
.RI "virtual \fBDataParameter::ParameterType\fP \fBgetParameterType\fP () const"
.br
.RI "getParameterType "
.ti -1c
.RI "virtual QByteArray \fBgetByteArray\fP () const"
.br
.RI "getByteArray "
.ti -1c
.RI "virtual std::string \fBgetDescription\fP () const"
.br
.RI "getDescription "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBParameterMemoryWrite\fP class\&. 
.PP
Definition at line 15 of file parameter_memory_write\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DataParameter::ParameterMemoryWrite::ParameterMemoryWrite ()"

.PP
\fBParameterMemoryWrite\fP\&. 
.PP
Definition at line 6 of file parameter_memory_write\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QByteArray DataParameter::ParameterMemoryWrite::getByteArray () const\fC [virtual]\fP"

.PP
getByteArray 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Implements \fBDataParameter::AbstractParameter\fP\&.
.PP
Definition at line 22 of file parameter_memory_write\&.cpp\&.
.SS "std::string DataParameter::ParameterMemoryWrite::getDescription () const\fC [virtual]\fP"

.PP
getDescription 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Implements \fBDataParameter::AbstractParameter\fP\&.
.PP
Definition at line 16 of file parameter_memory_write\&.cpp\&.
.SS "\fBParameterType\fP DataParameter::ParameterMemoryWrite::getParameterType () const\fC [virtual]\fP"

.PP
getParameterType 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Implements \fBDataParameter::AbstractParameter\fP\&.
.PP
Definition at line 11 of file parameter_memory_write\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
