.TH "ExceptionResponse" 3 "Tue Jun 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExceptionResponse
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exception_response\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExceptionResponse\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file exception_response\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExceptionResponse::ExceptionResponse ()"

.PP
Definition at line 3 of file exception_response\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
