.TH "Window_MunkPowerSupply/mainwindow.cpp" 3 "Mon Jun 19 2017" "ECM Control System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Window_MunkPowerSupply/mainwindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br
\fC#include 'library_munk_power_supply/data/type_segment_level\&.h'\fP
.br
\fC#include 'library_munk_power_supply/data/type_segment_mode\&.h'\fP
.br
\fC#include 'library_munk_power_supply/data/type_read_write\&.h'\fP
.br
\fC#include 'library_munk_power_supply/data/type_prescalar_power\&.h'\fP
.br
\fC#include 'library_munk_power_supply/data_registers/segment_time_general\&.h'\fP
.br
\fC#include 'data_registers/segment_time_detailed\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for ECM Control System from the source code\&.
