.TH "Window_MunkPowerSupply/mainwindow.h" 3 "Mon Jun 19 2017" "ECM Control System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Window_MunkPowerSupply/mainwindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include 'library_munk_power_supply_global\&.h'\fP
.br
\fC#include <QMainWindow>\fP
.br
\fC#include <QByteArray>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ECM Control System from the source code\&.
