.TH "MainWindow" 3 "Tue Jun 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mainwindow\&.h>\fP
.PP
Inherits QMainWindow, and QMainWindow\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBgenerateMessage\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~MainWindow\fP ()"
.br
.ti -1c
.RI "\fBMainWindow\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~MainWindow\fP ()"
.br
.ti -1c
.RI "void \fBsetupUiElements\fP ()"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBon_pushButton_generatemsg_clicked\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBUi::MainWindow\fP * \fBui\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file mainwindow\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MainWindow::MainWindow (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 4 of file mainwindow\&.cpp\&.
.SS "MainWindow::~MainWindow ()"

.PP
Definition at line 12 of file mainwindow\&.cpp\&.
.SS "MainWindow::MainWindow (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "MainWindow::~MainWindow ()"

.SH "Member Function Documentation"
.PP 
.SS "void MainWindow::generateMessage ()\fC [slot]\fP"

.PP
Definition at line 54 of file mainwindow\&.cpp\&.
.SS "void MainWindow::on_pushButton_generatemsg_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 78 of file mainwindow\&.cpp\&.
.SS "void MainWindow::setupUiElements ()"

.PP
Definition at line 23 of file mainwindow\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBUi::MainWindow\fP * MainWindow::ui\fC [private]\fP"

.PP
Definition at line 28 of file mainwindow\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
