.TH "src/Window_MunkPowerSupply/mainwindow.cpp" 3 "Tue Jun 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Window_MunkPowerSupply/mainwindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br
\fC#include 'library_munk_power_supply/data/type_segment_level\&.h'\fP
.br
\fC#include 'library_munk_power_supply/data/type_segment_mode\&.h'\fP
.br
\fC#include 'library_munk_power_supply/data/type_read_write\&.h'\fP
.br
\fC#include 'library_munk_power_supply/data/type_prescalar_power\&.h'\fP
.br
\fC#include 'library_munk_power_supply/data_registers/segment_time_general\&.h'\fP
.br
\fC#include 'data_registers/segment_time_detailed\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
