.TH "MunkPowerSupply" 3 "Tue Jun 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MunkPowerSupply
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <munk_power_supply\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMunkPowerSupply\fP ()"
.br
.ti -1c
.RI "void \fBgenerateMessages\fP (const \fBDataParameter::SegmentTimeDetailed\fP &detailedSegmentData)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBgenerateSetpointMessages\fP (const std::map< \fBData::RegisterDataObject\fP, \fBData::SegmentLevel\fP > &map, const \fBData::SegmentMode\fP &mode, std::vector< \fBDataParameter::SegmentVoltageSetpoint\fP > &VMsgs, std::vector< \fBDataParameter::SegmentCurrentSetpoint\fP > &IMsgs)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file munk_power_supply\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MunkPowerSupply::MunkPowerSupply ()"

.PP
Definition at line 3 of file munk_power_supply\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void MunkPowerSupply::generateMessages (const \fBDataParameter::SegmentTimeDetailed\fP & detailedSegmentData)"

.PP
Definition at line 47 of file munk_power_supply\&.cpp\&.
.SS "void MunkPowerSupply::generateSetpointMessages (const std::map< \fBData::RegisterDataObject\fP, \fBData::SegmentLevel\fP > & map, const \fBData::SegmentMode\fP & mode, std::vector< \fBDataParameter::SegmentVoltageSetpoint\fP > & VMsgs, std::vector< \fBDataParameter::SegmentCurrentSetpoint\fP > & IMsgs)\fC [private]\fP"

.PP
Definition at line 31 of file munk_power_supply\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
