.TH "library_munk_power_supply/munk_power_supply.h" 3 "Mon Jun 19 2017" "ECM Control System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
library_munk_power_supply/munk_power_supply.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include 'library_munk_power_supply_global\&.h'\fP
.br
\fC#include 'data_registers/segment_time_general\&.h'\fP
.br
\fC#include 'data_registers/segment_time_detailed\&.h'\fP
.br
\fC#include 'data_registers/segment_voltage_setpoint\&.h'\fP
.br
\fC#include 'data_registers/segment_current_setpoint\&.h'\fP
.br
\fC#include 'data/type_current_voltage_prescale\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMunkPowerSupply\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ECM Control System from the source code\&.
