.TH "library_munk_power_supply/data/register_data_object.h" 3 "Mon Jun 19 2017" "ECM Control System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
library_munk_power_supply/data/register_data_object.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBData::RegisterDataObject\fP"
.br
.RI "The \fBRegisterDataObject\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBData\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ECM Control System from the source code\&.
