.TH "library_munk_power_supply/data_registers/segment_time_data_general.h" 3 "Mon Jun 19 2017" "ECM Control System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
library_munk_power_supply/data_registers/segment_time_data_general.h
.SH SYNOPSIS
.br
.PP
\fC#include <data/type_prescalar_power\&.h>\fP
.br
\fC#include <data/type_segment_level\&.h>\fP
.br
\fC#include <data/type_segment_mode\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataParameter::SegmentTimeDataGeneral\fP"
.br
.RI "The \fBSegmentTimeDataGeneral\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBDataParameter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ECM Control System from the source code\&.
