.TH "library_munk_power_supply/data_registers/segment_time_data_detailed.cpp" 3 "Mon Jun 19 2017" "ECM Control System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
library_munk_power_supply/data_registers/segment_time_data_detailed.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'segment_time_data_detailed\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBDataParameter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ECM Control System from the source code\&.
