.TH "library_munk_power_supply/data_registers/segment_voltage_setpoint.h" 3 "Mon Jun 19 2017" "ECM Control System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
library_munk_power_supply/data_registers/segment_voltage_setpoint.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'abstract_parameter\&.h'\fP
.br
\fC#include 'data/type_segment_level\&.h'\fP
.br
\fC#include 'data/type_segment_mode\&.h'\fP
.br
\fC#include 'data/type_current_voltage_prescale\&.h'\fP
.br
\fC#include 'data/type_voltage_set\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataParameter::SegmentVoltageSetpoint\fP"
.br
.RI "The \fBSegmentVoltageSetpoint\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBDataParameter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ECM Control System from the source code\&.
