.TH "src/library_munk_power_supply/data_registers/segment_time_detailed.h" 3 "Tue Jun 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/library_munk_power_supply/data_registers/segment_time_detailed.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'abstract_parameter\&.h'\fP
.br
\fC#include 'segment_time_data_detailed\&.h'\fP
.br
\fC#include 'segment_time_general\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataParameter::SegmentTimeDetailed\fP"
.br
.RI "The \fBSegmentTimeDetailed\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBDataParameter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
