.TH "src/library_munk_power_supply/data_registers/segment_time_detailed.cpp" 3 "Tue Jun 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/library_munk_power_supply/data_registers/segment_time_detailed.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'segment_time_detailed\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBDataParameter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
