.TH "src/library_munk_power_supply/data_registers/segment_time_data_detailed.h" 3 "Tue Jun 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/library_munk_power_supply/data_registers/segment_time_data_detailed.h
.SH SYNOPSIS
.br
.PP
\fC#include <data/type_prescalar_power\&.h>\fP
.br
\fC#include <data/type_segment_level\&.h>\fP
.br
\fC#include <data/type_segment_mode\&.h>\fP
.br
\fC#include <data/register_data_object\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataParameter::SegmentTimeDataDetailed\fP"
.br
.RI "The \fBSegmentTimeDataDetailed\fP class is the class that the user should implement when establishing a segments data\&. The data contained in here shall be mapped later on to the correct levels and establish the necessary current/voltage messages for interacting with the munk power supply\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBDataParameter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
