.TH "src/library_munk_power_supply/data/type_read_write.h" 3 "Tue Jun 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/library_munk_power_supply/data/type_read_write.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBData\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBData::ReadWriteType\fP { \fBData::ReadWriteType::READ\fP = 03, \fBData::ReadWriteType::WRITE\fP = 16 }
.RI "The ReadWriteType enum\&. ""
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBData::ReadWriteTypeToString\fP (const ReadWriteType &type)"
.br
.RI "ReadWriteTypeToString\&. "
.ti -1c
.RI "ReadWriteType \fBData::ReadWriteTypeFromString\fP (const std::string &str)"
.br
.RI "ReadWriteTypeFromString\&. "
.ti -1c
.RI "std::vector< std::string > \fBData::getListOfReadWriteType\fP ()"
.br
.RI "getListOfReadWriteType "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
