.TH "src/library_munk_power_supply/data/type_current_voltage_prescale.h" 3 "Tue Jun 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/library_munk_power_supply/data/type_current_voltage_prescale.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBData\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBData::SegmentVIPower\fP { \fBData::SegmentVIPower::ONE\fP = 0, \fBData::SegmentVIPower::ONE_HUNDREDTH\fP = 1, \fBData::SegmentVIPower::ONE_TENTH\fP = 2, \fBData::SegmentVIPower::TEN\fP = 3, \fBData::SegmentVIPower::ONE_HUNDRED\fP = 5 }
.RI "The SegmentVIPower enum\&. ""
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBData::SegmentVIPowerToString\fP (const SegmentVIPower &type)"
.br
.RI "SegmentVIPowerToString\&. "
.ti -1c
.RI "SegmentVIPower \fBData::SegmentVIPowerFromString\fP (const std::string &str)"
.br
.RI "SegmentVIPowerFromString\&. "
.ti -1c
.RI "std::vector< std::string > \fBData::getListOfSegmentVIPower\fP ()"
.br
.RI "getListOfSegmentVIPower "
.ti -1c
.RI "uint32_t \fBData::SegmenVIPowerToBitArray\fP (const SegmentVIPower &type, const uint32_t &bitArray)"
.br
.RI "SegmenVIPowerToBitArray\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
