.TH "src/library_munk_power_supply/data/type_segment_parameter.h" 3 "Tue Jun 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/library_munk_power_supply/data/type_segment_parameter.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBData\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBData::SegmentParameter\fP { \fBData::SegmentParameter::SEGMENT1\fP = 4170, \fBData::SegmentParameter::SEGMENT2\fP = 4171, \fBData::SegmentParameter::SEGMENT3\fP = 4172, \fBData::SegmentParameter::SEGMENT4\fP = 4173, \fBData::SegmentParameter::SEGMENT5\fP = 4174, \fBData::SegmentParameter::SEGMENT6\fP = 4175, \fBData::SegmentParameter::SEGMENT7\fP = 4176, \fBData::SegmentParameter::SEGMENT8\fP = 4178, \fBData::SegmentParameter::SEGMENT9\fP = 4179, \fBData::SegmentParameter::SEGMENT10\fP = 4180, \fBData::SegmentParameter::SEGMENT11\fP = 4181, \fBData::SegmentParameter::SEGMENT12\fP = 4182, \fBData::SegmentParameter::SEGMENT13\fP = 4183, \fBData::SegmentParameter::SEGMENT14\fP = 4184, \fBData::SegmentParameter::SEGMENT15\fP = 4185, \fBData::SegmentParameter::SEGMENT16\fP = 4186 }
.RI "The SegmentParameter enum\&. ""
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBData::ReadWriteTypeToString\fP (const ReadWriteType &type)"
.br
.RI "ReadWriteTypeToString\&. "
.ti -1c
.RI "ReadWriteType \fBData::ReadWriteTypeFromString\fP (const std::string &str)"
.br
.RI "ReadWriteTypeFromString\&. "
.ti -1c
.RI "std::vector< std::string > \fBData::getListOfReadWriteType\fP ()"
.br
.RI "getListOfReadWriteType "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
