.TH "src/library_munk_power_supply/data/type_prescalar_power.h" 3 "Tue Jun 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/library_munk_power_supply/data/type_prescalar_power.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBData\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBData::SegmentPower\fP { \fBData::SegmentPower::ONE\fP = 0, \fBData::SegmentPower::TEN\fP = 1, \fBData::SegmentPower::ONE_HUNDRED\fP = 2, \fBData::SegmentPower::ONE_THOUSAND\fP = 3, \fBData::SegmentPower::TEN_THOUSAND\fP = 4 }
.RI "The SegmentPower enum\&. ""
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBData::SegmentPowerToString\fP (const SegmentPower &type)"
.br
.RI "SegmentPowerToString\&. "
.ti -1c
.RI "SegmentPower \fBData::SegmentPowerFromString\fP (const std::string &str)"
.br
.RI "SegmentPowerFromString\&. "
.ti -1c
.RI "std::vector< std::string > \fBData::getListOfSegmentPower\fP ()"
.br
.RI "getListOfSegmentPower "
.ti -1c
.RI "uint32_t \fBData::SegmentPowerToBitArray\fP (const SegmentPower &type, const uint32_t &bitArray)"
.br
.RI "SegmentPowerToBitArray\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
