.TH "src/library_munk_power_supply/data/type_response_exception.h" 3 "Tue Jun 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/library_munk_power_supply/data/type_response_exception.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBData\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBData::TypeResponseException\fP { \fBData::TypeResponseException::ILLEGAL_FUNCTION\fP = 0, \fBData::TypeResponseException::ILLEGAL_DATA_ADDRESS\fP = 1, \fBData::TypeResponseException::ILLEGAL_DATA_VALUE\fP = 2 }
.RI "The TypeResponseException enum\&. ""
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBData::TypeResponseExceptionToString\fP (const TypeResponseException &type)"
.br
.RI "TypeResponseExceptionToString\&. "
.ti -1c
.RI "TypeResponseException \fBData::TypeResponseExceptionFromString\fP (const std::string &str)"
.br
.RI "TypeResponseExceptionFromString\&. "
.ti -1c
.RI "std::vector< std::string > \fBData::getListOfTypeResponseException\fP ()"
.br
.RI "getListOfTypeResponseException "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
