.TH "Ui::MainWindow" 3 "Mon Jun 19 2017" "ECM Control System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::MainWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_mainwindow\&.h>\fP
.PP
Inherits \fBUi_MainWindow\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 64 of file ui_mainwindow\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECM Control System from the source code\&.
