.TH "ECM_MainWindow/ui_mainwindow.h" 3 "Mon Jun 19 2017" "ECM Control System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ECM_MainWindow/ui_mainwindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QVariant>\fP
.br
\fC#include <QtWidgets/QAction>\fP
.br
\fC#include <QtWidgets/QApplication>\fP
.br
\fC#include <QtWidgets/QButtonGroup>\fP
.br
\fC#include <QtWidgets/QHeaderView>\fP
.br
\fC#include <QtWidgets/QMainWindow>\fP
.br
\fC#include <QtWidgets/QMenuBar>\fP
.br
\fC#include <QtWidgets/QStatusBar>\fP
.br
\fC#include <QtWidgets/QToolBar>\fP
.br
\fC#include <QtWidgets/QWidget>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUi_MainWindow\fP"
.br
.ti -1c
.RI "class \fBUi::MainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ECM Control System from the source code\&.
