.TH "ValidResponse" 3 "Tue Jun 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ValidResponse
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <valid_response\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValidResponse\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file valid_response\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ValidResponse::ValidResponse ()"

.PP
Definition at line 3 of file valid_response\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
