#ifndef LIBRARY_WESTINGHOUSE510_GLOBAL_H
#define LIBRARY_WESTINGHOUSE510_GLOBAL_H

#ifdef _MSC_VER
#  if defined(LIBRARY_WESTINGHOUSE510_LIBRARY)
#    define LIBRARY_WESTINGHOUSE510SHARED_EXPORT __declspec(dllexport)
#  else
#    define LIBRARY_WESTINGHOUSE510SHARED_EXPORT __declspec(dllexport)
#  endif
#else
#  define LIBRARY_WESTINGHOUSE510SHARED_EXPORT
#endif

#endif // LIBRARY_WESTINGHOUSE510_GLOBAL_H
