#ifndef WESTINGHOUSE_MESSAGE_FRAMING_H
#define WESTINGHOUSE_MESSAGE_FRAMING_H


namespace comms_WestinghousePump{

enum class FramingState{
    WAITING,
    RECIEVED_PUMP_ADDRESS,
    RECEIVED_EXCEPTION_FUNCTION_CODE,
    RECEIVED_STD_FUNCTION_CODE_READ,
    RECEIVED_STD_FUNCTION_CODE_WRITE,
    RECEIVED_EXCEPTION_CODE,
    RECEIVED_PAYLOAD,
    RECEIVED_LAST_PAYLOAD,
    RECEIVED_CRC_LOW,
    RECEIVED_CRC_HIGH,
    RECEIVED_ENTIRE_MESSAGE
};

} //end of namespace comms_WestinghousePump


#endif // WESTINGHOUSE_MESSAGE_FRAMING_H
