#ifndef LIBRARY_QMODBUS_GLOBAL_H
#define LIBRARY_QMODBUS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBRARY_QMODBUS_LIBRARY)
#  define LIBRARY_QMODBUSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBRARY_QMODBUSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBRARY_QMODBUS_GLOBAL_H
