#ifndef PLCMESSAGE_MESSAGE_FRAMING_H
#define PLCMESSAGE_MESSAGE_FRAMING_H


namespace comms_PLC{

enum class PLCMessageFramingState{
    WAITING,
    RECIEVED_PUMP_ADDRESS,
    RECEIVED_EXCEPTION_FUNCTION_CODE,
    RECEIVED_STD_FUNCTION_CODE_READ,
    RECEIVED_STD_FUNCTION_CODE_WRITE,
    RECEIVED_EXCEPTION_CODE,
    RECEIVED_PAYLOAD,
    RECEIVED_LAST_PAYLOAD,
    RECEIVED_CRC_LOW,
    RECEIVED_CRC_HIGH,
    RECEIVED_ENTIRE_MESSAGE
};

} //end of namespace comms_PLC


#endif // PLCMESSAGE_MESSAGE_FRAMING_H
